test_that("empirical.prec: MAD over the record and Allan per UniqueID", {
  data(manID.UGGA)
  set.seed(1)
  x <- data.frame(UniqueID = rep(c("a", "b"), each = 600), flag = 1, camp = rep(c("x", "y"), each = 600),
                  CH4dry_ppb = c(2000 + 0.5 * (1:600) + rnorm(600, 0, 1.5), 2000 + rnorm(600, 0, 3)))
  m <- empirical.prec(x, "CH4dry_ppb")
  expect_equal(names(m), c("prec", "n"))
  expect_equal(m$n, 1199L)
  g <- empirical.prec(x, "CH4dry_ppb", by = "camp")
  expect_equal(g$camp, c("x", "y"))
  expect_equal(g$prec, c(1.5, 3), tolerance = 0.15)
  a <- empirical.prec(x, "CH4dry_ppb", method = "allan")
  expect_equal(a$UniqueID, c("a", "b"))
  expect_equal(a$prec, c(1.5, 3), tolerance = 0.1)
  expect_s3_class(empirical.prec(manID.UGGA, "CH4dry_ppb", method = "allan"), "data.frame")
  expect_error(empirical.prec(x, "nope"), "gastype")
})

test_that("MDF and best.flux accept conf; default behaviour unchanged", {
  expect_equal(MDF(0.9, 300, 0.7), 0.9 / 300 * 0.7)
  expect_equal(MDF(0.9, 300, 0.7, conf = 0.95), qnorm(0.975) * 0.9 / 300 * 0.7)
  expect_error(MDF(0.9, 300, 0.7, conf = 2), "conf")
  data(manID.UGGA)
  r0 <- goFlux(manID.UGGA, "CH4dry_ppb")
  r1 <- goFlux(manID.UGGA, "CH4dry_ppb", conf = 0.95)
  expect_equal(r1$MDF, r0$MDF * qnorm(0.975))
  b0 <- best.flux(r0); b1 <- best.flux(r0, conf = 0.95)
  expect_equal(b1$MDF, b0$MDF * qnorm(0.975)); expect_equal(unique(b1$MDF.conf), 0.95)
  expect_false("MDF.conf" %in% names(b0))
})
